apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domainnonjrf
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: preethig8@gmail.com
spec:
  project: default
  source:
    repoURL: https://github.com/preethignanesh/argo-cd.git
    targetRevision: HEAD
    path: domainnonjrf
  destination:
    server: https://kubernetes.default.svc
    namespace: domainnonjrf-ns
  ignoreDifferences:
  - group: "weblogic.oracle"
    kind: "Domain"
    jsonPointers:
    - /metadata/generation
    - /metadata/managedFields
    - /metadata/resourceVersion
    - /metadata/annotations
    - /status
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    syncOptions:
    - RespectIgnoreDifferences=true
