apiVersion: weblogic.oracle/v8
kind: Domain
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"weblogic.oracle/v8","kind":"Domain","metadata":{"annotations":{},"creationTimestamp":"2022-03-15T04:55:11Z","generation":9,"labels":{"app.kubernetes.io/instance":"domainnonjrf","weblogic.domainUID":"domainnonjrf-uid"},"managedFields":[{"apiVersion":"weblogic.oracle/v8","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:weblogic.domainUID":{}}}},"manager":"OpenAPI-Generator","operation":"Update","time":"2022-03-15T04:55:11Z"},{"apiVersion":"weblogic.oracle/v8","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:clusters":{},"f:conditions":{},"f:introspectJobFailureCount":{},"f:replicas":{},"f:servers":{},"f:startTime":{}}},"manager":"Kubernetes Java Client","operation":"Update","time":"2022-03-15T05:01:37Z"},{"apiVersion":"weblogic.oracle/v8","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{"f:app.kubernetes.io/instance":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2022-03-16T09:18:49Z"}],"name":"domainnonjrf","namespace":"domainnonjrf-ns","resourceVersion":"17454155","selfLink":"/apis/weblogic.oracle/v8/namespaces/domainnonjrf-ns/domains/domainnonjrf","uid":"20c17493-5186-40bc-b507-bdd423a70ac2"},"spec":{"adminServer":{"serverPod":{"env":[{"name":"USER_MEM_ARGS","value":"-Xms256m -Xmx512m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom"},{"name":"JAVA_OPTIONS","value":"-Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false"}]},"serverStartState":"RUNNING"},"clusters":[{"clusterName":"domainnonjrf-cluster","replicas":1,"serverPod":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"weblogic.clusterName","operator":"In","values":["domainnonjrf-cluster"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"env":[{"name":"USER_MEM_ARGS","value":"-XX:+UseContainerSupport -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom"},{"name":"JAVA_OPTIONS","value":"-Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false"}]},"serverStartState":"RUNNING"}],"configuration":{"introspectorJobActiveDeadlineSeconds":300,"model":{"configMap":"domainnonjrf-configmap","domainType":"WLS","runtimeEncryptionSecret":"domainnonjrf-runtime-encryption-secret"},"secrets":["domainnonjrf-password-secret"]},"dataHome":"/u01/shared/weblogic-domains/domainnonjrf/data/store","domainHome":"/u01/data/domains/domainnonjrf-uid","domainHomeSourceType":"FromModel","image":"iad.ocir.io/idivyfxzwa6h/wlschk/wls-base-image/domainnonjrf/122140:12.2.1.4.220118-220207-22-03-16_09-10-55","imagePullPolicy":"IfNotPresent","imagePullSecrets":[{"name":"ocirsecrets"}],"includeServerOutInPodLog":true,"logHome":"/u01/shared/weblogic-domains/domainnonjrf/logs","logHomeEnabled":true,"restartVersion":"1","serverPod":{"env":[{"name":"RESOURCE_PREFIX","value":"domainnonjrf"},{"name":"JAVA_OPTIONS","value":"-Dweblogic.StdoutDebugEnabled=false -Doracle.jdbc.fanEnabled=false "},{"name":"OKE_DOMAIN_NAME","value":"domainnonjrf"}],"nodeSelector":{"name":"wlschk-wls-np","usage":"weblogic"},"volumeMounts":[{"mountPath":"/u01/shared","name":"weblogic-domain-storage-volume"}],"volumes":[{"name":"weblogic-domain-storage-volume","persistentVolumeClaim":{"claimName":"domainnonjrf-oke-pvc"}}]},"serverStartPolicy":"IF_NEEDED","webLogicCredentialsSecret":{"name":"domainnonjrf-weblogic-credentials"}},"status":{"clusters":[{"clusterName":"domainnonjrf-cluster","maximumReplicas":9,"minimumReplicas":0,"readyReplicas":1,"replicas":1,"replicasGoal":1}],"conditions":[{"lastTransitionTime":"2022-03-16T09:26:00.289476Z","reason":"ServersReady","status":"True","type":"Available"}],"introspectJobFailureCount":0,"replicas":1,"servers":[{"desiredState":"RUNNING","health":{"activationTime":"2022-03-16T09:25:35.937000Z","overallHealth":"ok","subsystems":[{"subsystemName":"ServerRuntime","symptoms":[]}]},"nodeName":"10.0.4.7","serverName":"domainnonjrf-adminserver","state":"RUNNING"},{"clusterName":"domainnonjrf-cluster","desiredState":"RUNNING","health":{"activationTime":"2022-03-16T09:27:48.780000Z","overallHealth":"ok","subsystems":[{"subsystemName":"ServerRuntime","symptoms":[]}]},"nodeName":"10.0.4.7","serverName":"domainnonjrf-managed-server1","state":"RUNNING"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server2"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server3"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server4"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server5"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server6"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server7"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server8"},{"clusterName":"domainnonjrf-cluster","desiredState":"SHUTDOWN","serverName":"domainnonjrf-managed-server9"}],"startTime":"2022-03-15T04:55:11.667278Z"}}
  creationTimestamp: "2022-03-15T04:55:11Z"
  generation: 9
  labels:
    app.kubernetes.io/instance: domainnonjrf
    weblogic.domainUID: domainnonjrf-uid
  managedFields:
  - apiVersion: weblogic.oracle/v8
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:weblogic.domainUID: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2022-03-15T04:55:11Z"
  - apiVersion: weblogic.oracle/v8
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:clusters: {}
        f:conditions: {}
        f:introspectJobFailureCount: {}
        f:replicas: {}
        f:servers: {}
        f:startTime: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2022-03-15T05:01:37Z"
  - apiVersion: weblogic.oracle/v8
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app.kubernetes.io/instance: {}
    manager: argocd-application-controller
    operation: Update
    time: "2022-03-16T09:18:49Z"
  name: domainnonjrf
  namespace: domainnonjrf-ns
  resourceVersion: "17470384"
  selfLink: /apis/weblogic.oracle/v8/namespaces/domainnonjrf-ns/domains/domainnonjrf
  uid: 20c17493-5186-40bc-b507-bdd423a70ac2
spec:
  adminServer:
    serverPod:
      env:
      - name: USER_MEM_ARGS
        value: -Xms256m -Xmx512m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
      - name: JAVA_OPTIONS
        value: -Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true
          -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false
    serverStartState: RUNNING
  clusters:
  - clusterName: domainnonjrf-cluster
    replicas: 1
    serverPod:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: weblogic.clusterName
                  operator: In
                  values:
                  - domainnonjrf-cluster
              topologyKey: kubernetes.io/hostname
            weight: 100
      env:
      - name: USER_MEM_ARGS
        value: -XX:+UseContainerSupport -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
      - name: JAVA_OPTIONS
        value: -Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true
          -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false
    serverStartState: RUNNING
  configuration:
    introspectorJobActiveDeadlineSeconds: 300
    model:
      configMap: domainnonjrf-configmap
      domainType: WLS
      runtimeEncryptionSecret: domainnonjrf-runtime-encryption-secret
    secrets:
    - domainnonjrf-password-secret
  dataHome: /u01/shared/weblogic-domains/domainnonjrf/data/store
  domainHome: /u01/data/domains/domainnonjrf-uid
  domainHomeSourceType: FromModel
  image: iad.ocir.io/idivyfxzwa6h/wlschk/wls-base-image/domainnonjrf/122140:12.2.1.4.220118-220207-22-03-16_09-10-55
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: ocirsecrets
  includeServerOutInPodLog: true
  logHome: /u01/shared/weblogic-domains/domainnonjrf/logs
  logHomeEnabled: true
  restartVersion: "1"
  serverPod:
    env:
    - name: RESOURCE_PREFIX
      value: domainnonjrf
    - name: JAVA_OPTIONS
      value: '-Dweblogic.StdoutDebugEnabled=false -Doracle.jdbc.fanEnabled=false '
    - name: OKE_DOMAIN_NAME
      value: domainnonjrf
    nodeSelector:
      name: wlschk-wls-np
      usage: weblogic
    volumeMounts:
    - mountPath: /u01/shared
      name: weblogic-domain-storage-volume
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: domainnonjrf-oke-pvc
  serverStartPolicy: IF_NEEDED
  webLogicCredentialsSecret:
    name: domainnonjrf-weblogic-credentials
status:
  clusters:
  - clusterName: domainnonjrf-cluster
    maximumReplicas: 9
    minimumReplicas: 0
    readyReplicas: 1
    replicas: 1
    replicasGoal: 1
  conditions:
  - lastTransitionTime: "2022-03-16T09:26:00.289476Z"
    reason: ServersReady
    status: "True"
    type: Available
  introspectJobFailureCount: 0
  replicas: 1
  servers:
  - desiredState: RUNNING
    health:
      activationTime: "2022-03-16T09:25:35.937000Z"
      overallHealth: ok
      subsystems:
      - subsystemName: ServerRuntime
        symptoms: []
    nodeName: 10.0.4.7
    serverName: domainnonjrf-adminserver
    state: RUNNING
  - clusterName: domainnonjrf-cluster
    desiredState: RUNNING
    health:
      activationTime: "2022-03-16T09:27:48.780000Z"
      overallHealth: ok
      subsystems:
      - subsystemName: ServerRuntime
        symptoms: []
    nodeName: 10.0.4.7
    serverName: domainnonjrf-managed-server1
    state: RUNNING
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server2
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server3
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server4
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server5
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server6
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server7
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server8
  - clusterName: domainnonjrf-cluster
    desiredState: SHUTDOWN
    serverName: domainnonjrf-managed-server9
  startTime: "2022-03-15T04:55:11.667278Z"
