apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domainvzsync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/preethignanesh/argo-cd.git
    targetRevision: HEAD
    path: domainvzsync
  destination:
    server: https://kubernetes.default.svc
    namespace: domainvzsync-ns
  ignoreDifferences:
  - group: "weblogic.oracle"
    kind: "Domain"
    jsonPointers:
    - /metadata/generation
    - /metadata/managedFields
    - /metadata/resourceVersion
    - /metadata/annotations
    - /status
  - group: "core.oam.dev"
    kind: "ApplicationConfiguration"
    jsonPointers:
    - /spec/components
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    syncOptions:
    - RespectIgnoreDifferences=true
