apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: bobby-wls
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoWebLogicWorkload
    spec:
      template:
        apiVersion: weblogic.oracle/v9
        metadata:
          name: bobbys-front-end
          labels:
            weblogic.resourceVersion: domain-v9
            weblogic.domainUID: bobbys-front-end
        spec:
          adminServer:
            adminChannelPortForwardingEnabled: true
          domainUID: bobbys-front-end
          domainHome: /u01/oracle/user_projects/domains/bobbys-front-end
          image: container-registry.oracle.com/middleware/weblogic:12.2.1.4
          imagePullSecrets:
            - name: bobs-books-repo-credentials
          domainHomeSourceType: "FromModel"
          includeServerOutInPodLog: true
          replicas: 1
          webLogicCredentialsSecret:
            name: bobbys-front-end-weblogic-credentials
          clusters:
            - name: bobbys-front-end-cluster-1
          configuration:
            introspectorJobActiveDeadlineSeconds: 600
            model:
              auxiliaryImages:
                - image: container-registry.oracle.com/verrazzano/example-bobbys-front-end:1.0.0-1-20220608153526-843e168
              runtimeEncryptionSecret: bobbys-front-end-runtime-encrypt-secret
          monitoringExporter:
            imagePullPolicy: IfNotPresent
            configuration:
              metricsNameSnakeCase: true
              domainQualifier: true
              queries:
                - key: name
                  keyName: location
                  prefix: wls_server_
                  applicationRuntimes:
                    key: name
                    keyName: app
                    componentRuntimes:
                      prefix: wls_webapp_config_
                      type: WebAppComponentRuntime
                      key: name
                      values: [ deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount ]
                      servlets:
                        prefix: wls_servlet_
                        key: servletName
                - JVMRuntime:
                    prefix: wls_jvm_
                    key: name
          serverPod:
            labels:
              app: bobbys-front-end
              version: v1
            env:
              - name: JAVA_OPTIONS
                value: "-Dweblogic.StdoutDebugEnabled=false"
              - name: USER_MEM_ARGS
                value: "-Djava.security.egd=file:/dev/./urandom"
              - name: HELIDON_HOSTNAME
                value: "bobbys-helidon-stock-application"
              - name: HELIDON_PORT
                value: "8080"
              - name: WL_HOME
                value: /u01/oracle/wlserver
              - name: MW_HOME
                value: /u01/oracle
      clusters:
        - apiVersion: weblogic.oracle/v1
          metadata:
            name: bobbys-front-end-cluster-1
            labels:
              weblogic.resourceVersion: domain-v1
              weblogic.domainUID: bobbys-front-end
          spec:
            clusterName: cluster-1
