apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: bobs-orders-wls
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoWebLogicWorkload
    spec:
      template:
        apiVersion: weblogic.oracle/v9
        metadata:
          name: bobs-bookstore
          labels:
            weblogic.resourceVersion: domain-v9
            weblogic.domainUID: bobs-bookstore
        spec:
          adminServer:
            adminChannelPortForwardingEnabled: true
          domainUID: bobs-bookstore
          domainHome: /u01/oracle/user_projects/domains/bobs-bookstore
          domainHomeSourceType: FromModel
          image: container-registry.oracle.com/middleware/weblogic:12.2.1.4
          includeServerOutInPodLog: true
          replicas: 1
          webLogicCredentialsSecret:
            name: bobs-bookstore-weblogic-credentials
          imagePullSecrets:
            - name: bobs-books-repo-credentials
          clusters:
            - name: bobs-bookstore-cluster-1
          configuration:
            introspectorJobActiveDeadlineSeconds: 600
            model:
              auxiliaryImages:
                - image: container-registry.oracle.com/verrazzano/example-bobs-books-order-manager:1.0.0-1-20220608153526-843e168
              configMap: bobs-bookstore-wdt-config-map
              runtimeEncryptionSecret: bobs-bookstore-runtime-encrypt-secret
            secrets:
              - mysql-credentials
          monitoringExporter:
            imagePullPolicy: IfNotPresent
            configuration:
              metricsNameSnakeCase: true
              domainQualifier: true
              queries:
                - key: name
                  keyName: location
                  prefix: wls_server_
                  applicationRuntimes:
                    key: name
                    keyName: app
                    componentRuntimes:
                      prefix: wls_webapp_config_
                      type: WebAppComponentRuntime
                      key: name
                      values: [ deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount ]
                      servlets:
                        prefix: wls_servlet_
                        key: servletName
                - JVMRuntime:
                    prefix: wls_jvm_
                    key: name
          serverPod:
            labels:
              app: bobs-bookstore
              version: v1
            env:
              - name: JAVA_OPTIONS
                value: "-Dweblogic.StdoutDebugEnabled=false"
              - name: USER_MEM_ARGS
                value: "-Djava.security.egd=file:/dev/./urandom "
              - name: WL_HOME
                value: /u01/oracle/wlserver
              - name: MW_HOME
                value: /u01/oracle
      clusters:
        - apiVersion: weblogic.oracle/v1
          metadata:
            name: bobs-bookstore-cluster-1
            labels:
              weblogic.resourceVersion: domain-v1
              weblogic.domainUID: bobs-bookstore
          spec:
            clusterName: cluster-1
