# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: bobs-books
  annotations:
    version: v1.0.0
    description: "Bob's Books"
spec:
  components:
    - componentName: robert-helidon
    - componentName: robert-coh
    - componentName: bobby-coh
    - componentName: bobby-helidon
    - componentName: bobby-wls
    - componentName: bobs-orders-wls
    - componentName: bobs-orders-configmap
    - componentName: bobs-mysql-deployment
    - componentName: bobs-mysql-service
    - componentName: bobs-mysql-configmap
