apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: robert-coh
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoCoherenceWorkload
    spec:
      template:
        metadata:
          name: roberts-coherence
        spec:
          labels:
            app: robert-coh
            version: v1
          replicas: 2
          image: container-registry.oracle.com/verrazzano/example-roberts-coherence:1.0.0-1-20210728181814-eb1e622
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: bobs-books-repo-credentials
          env:
            - name: BACKEND_PORT
              value: "8001"
            - name: BACKEND_HOSTNAME
              value: bobs-bookstore-cluster-cluster-1
            - name: TRACING_HOST
              value: "jaeger-collector"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
          jvm:
            memory:
              heapSize: 1g
            args:
              - "-Dcoherence.k8s.operator.health.wait.dcs=false"
          coherence:
            metrics:
              enabled: true
          ports:
            - name: tcp-extend
              port: 9000
              service:
                name: roberts-coherence-extend
