apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: robert-helidon
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: robert-helidon
      labels:
        app: robert-helidon
        version: v1
    spec:
      deploymentTemplate:
        metadata:
          name: robert-helidon
        podSpec:
          containers:
            - name: robert-helidon-stock-application
              image: container-registry.oracle.com/verrazzano/example-roberts-helidon-stock-application:1.0.0-1-20210728181814-eb1e622
              imagePullPolicy: IfNotPresent
              ports:
                - name: http
                  containerPort: 8080
              env:
                - name: COH_CLUSTER
                  value: roberts-coherence
                - name: COH_CACHE_CONFIG
                  value: coherence-cache-config.xml
                - name: COH_POF_CONFIG
                  value: pof-config.xml
          imagePullSecrets:
            - name: bobs-books-repo-credentials
