apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: domainvz-appconf
  namespace: domainvz-ns
  annotations:
    version: v1.1.0
spec:
  components:
    - componentName: domainvz
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            spec:
              rules:
                - paths:
                    - path: “/domainvz”
                      pathType: Prefix
