apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: domainvz
  namespace: domainvz-ns
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoWebLogicWorkload
    spec:
      template:
        metadata:
          name: domainvz
          namespace: domainvz-ns
        spec:
          adminServer:
            adminChannelPortForwardingEnabled: true
            serverPod:
              env:
              - name: USER_MEM_ARGS
                value: -Xms256m -Xmx512m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
              - name: JAVA_OPTIONS
                value: -Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true
                  -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false
            serverStartState: RUNNING
          clusters:
          - clusterName: domainvz-cluster
            replicas: 1
            serverPod:
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: weblogic.clusterName
                          operator: In
                          values:
                          - domainvz-cluster
                      topologyKey: kubernetes.io/hostname
                    weight: 100
              env:
              - name: USER_MEM_ARGS
                value: -XX:+UseContainerSupport -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
              - name: JAVA_OPTIONS
                value: -Dweblogic.store.file.LockEnabled=false -Dweblogic.rjvm.allowUnknownHost=true
                  -Dweblogic.security.remoteAnonymousRMIT3Enabled=false -Dweblogic.security.remoteAnonymousRMIIIOPEnabled=false
            serverStartState: RUNNING
          configuration:
            introspectorJobActiveDeadlineSeconds: 300
            model:
              domainType: WLS
              runtimeEncryptionSecret: domainvz-runtime-encryption-secret
          dataHome: /u01/shared/weblogic-domains/domainvz/data/store
          domainHome: /u01/data/domains/domainvz-uid
          domainHomeSourceType: FromModel
          domainUID: domainvz-uid
          image: iad.ocir.io/idivyfxzwa6h/wls0328/wls-base-image/domainvz/122140:domainvz-22-03-29_11-31-32
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: ocirsecrets
          includeServerOutInPodLog: true
          logHome: /u01/shared/weblogic-domains/domainvz/logs
          logHomeEnabled: true
          monitoringExporter:
            image: iad.ocir.io/idivyfxzwa6h/wls0328/infra/weblogic-monitoring-exporter:2.0.4
            imagePullPolicy: IfNotPresent
          restartVersion: '1'
          serverPod:
            env:
            - name: RESOURCE_PREFIX
              value: domainvz
            - name: JAVA_OPTIONS
              value: '-Dweblogic.StdoutDebugEnabled=false -Doracle.jdbc.fanEnabled=false '
            - name: OKE_DOMAIN_NAME
              value: domainvz
            labels:
              app: domainvz
            volumeMounts:
            - mountPath: /u01/shared
              name: weblogic-domain-storage-volume
            volumes:
            - name: weblogic-domain-storage-volume
              persistentVolumeClaim:
                claimName: domainvz-oke-pvc
          serverStartPolicy: IF_NEEDED
          webLogicCredentialsSecret:
            name: domainvz-weblogic-credentials
